name: LintAndBuild
on: [push]
jobs:
  Lint-And-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run lint
      - run: npm run atlas
      - run: npm run build
